development: &default
  adapter: mysql2
  encoding: utf8
  database: humble_store_dev
  host: localhost
  username: humble_store
  password: '!QAZ2wsx'


test: &TEST
  <<: *default
  database: humble_store_test

production: &PROD
  adapter: mysql2
  encoding: utf8
  database: humble_store_prod
  host: localhost
  username: humble_store
  password: '!QAZ2wsx'